apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: calmmopey/github-runner-worker:arm64
        env:
        - name: GITHUB_OWNER
          value: andycockers
        - name: GITHUB_REPOSITORY
          value: gcp-automation
        - name: GITHUB_PAT # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: github-pat
              key: pat
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock