apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-gcp-automation-dind
  labels:
    app: github-runner-gcp-automation-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-gcp-automation-dind
  template:
    metadata:
      labels:
        app: github-runner-gcp-automation-dind
    spec:
      containers:
      - name: github-runner-gcp-automation
        image: calmmopey/github-runner-debian:arm64
        tty: true
        env:
        - name: GITHUB_OWNER
          value: andycockers
        - name: GITHUB_REPOSITORY
          value: gcp-automation
        - name: GITHUB_PAT # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: github-pat
              key: pat
      - name: docker
        image: docker
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        securityContext:
          privileged: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock