---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jenkins
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: jenkins
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          containers:
          - name: jenkins
            image: calmmopey/jenkins-arm64:2.289.1
            ports:
            - containerPort: 8080
            volumeMounts: 
            - name: jenkins-serviceaccount
              mountPath: "/jenkins" 
              readOnly: true
            - mountPath: /var/jenkins_home
              name: jenkins-home
              
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS 
              value: /jenkins/jenkins-test-project.json
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumes:
          - name: jenkins-serviceaccount
            secret:
              secretName: jenkins-serviceaccount
          - hostPath:
              path: /data/jenkins_home
            name: jenkins-home
              
