---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jenkins
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: jenkins
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          containers:
          - name: jenkins
            image: wolfman.crabdance.com/jenkins-arm:2.276
            ports:
            - containerPort: 8080
            volumeMounts:
            - mountPath: /tmp
              name: volume-0
              readOnly: false
            - mountPath: /var/jenkins_home
              name: jenkins-home
              
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/jenkins-test-project.json"
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumes:
          - hostPath:
              path: /tmp
            name: volume-0
          - hostPath:
              path: /data/jenkins_home
            name: jenkins-home
              