apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jenkins
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - cockerilla.plus.com
    secretName: jenkins-tls
  rules:
  - host: cockerilla.plus.com
    http:
      paths:
      - path: /jenkins
        pathType: ImplementationSpecific
        backend:
         service:
          name: jenkins
          port:
           number: 8080
