---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jenkins
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: jenkins
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          containers:
          - name: jenkins
            image: jenkins/jenkins:2.275-alpine
            ports:
            - containerPort: 8080
            volumeMounts:
              - name: jenkins-home
                mountPath: /var/jenkins_home
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/jenkins_home/sa.json"
            env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumes:
            - name: jenkins-home
              hostPath:
                path: /data/jenkins_home
