---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jenkins
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: jenkins
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          securityContext:
            fsGroup: 1000 
            runAsUser: 0
          containers:
          - name: jenkins
            image: jenkins/jenkins:2.303.1
            ports:
            - containerPort: 8080
            volumeMounts: 
            - mountPath: /var/jenkins_home
              name: pvc-a5e70e13-84a9-498a-a7b6-ea10fd4c43eb
              
            env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumes:
          - name: pvc-a5e70e13-84a9-498a-a7b6-ea10fd4c43eb
            persistentVolumeClaim:
              claimName: jenkins-pvc
              
