---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jenkins
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: jenkins
      template:
        metadata:
          labels:
            app: jenkins
        spec:
          containers:
          - name: jenkins
            image: jenkins/jenkins:2.275-alpine
            ports:
            - containerPort: 8080
            volumeMounts:
            - mountPath: /tmp
              name: volume-0
              readOnly: false  
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/jenkins-test-project.json"
            env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          volumes:
          - hostPath:
              path: /tmp
            name: volume-0