apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: secret
spec:
  containers:
  - name: secret-container
    image: calmmopey/worker-arm-buster
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS 
      value: /jenkins/jenkins-test-project.json 
    volumeMounts:
    - name: config-data
      mountPath: /data
    - name: jenkins-serviceaccount
      mountPath: "/jenkins" 
      readOnly: true
  initContainers:
  - name: init-myservice
    image: calmmopey/gcloud-sdk
    command: ['sh', '-c']
    args: 
      - gcloud auth activate-service-account andyc-963@jenkins-test-project-284609.iam.gserviceaccount.com --key-file=/jenkins/jenkins-test-project.json;
        gcloud secrets versions access latest --project=jenkins-test-project-284609 --secret=ansible-vault > /data/eranu.txt;
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS 
      value: /jenkins/jenkins-test-project.json 
    volumeMounts:
    - name: config-data
      mountPath: /data
    - name: jenkins-serviceaccount
      mountPath: "/jenkins" 
      readOnly: true
  volumes:
  - name: config-data
    emptyDir: {}
  - name: jenkins-serviceaccount
    secret:
      secretName: jenkins-serviceaccount
